/* ═══════════════════════════════════════════════════════════
 * EXERCISE_DB — B-8 운동 처방 DB
 *
 * 저작권 가이드 (인계메모 결정):
 *   - generic public domain 운동명만 (Squat / Lunge / Clamshell /
 *     Bird Dog 등 — 누구나 자유롭게 사용)
 *   - 학술 출처는 paraphrase + 출처 명시 (fair use)
 *   - FMS™/NASM™/SFMA™ 같은 브랜드 protocol verbatim 인용 금지
 *   - 운동 효과 설명은 일반 운동학 기반의 일상어 표현
 *
 * 카테고리:
 *   mobility  : 가동성 (스트레칭/SMR/CARs)
 *   stability : 안정성 (코어/호흡/관절 안정화)
 *   strength  : 근력 (저항·복합 운동)
 *   pattern   : 패턴 재교육 (hinge/squat/carry/balance)
 *
 * 부위 (regions): ankle / knee / hip / spine / shoulder / core
 *
 * 레벨 (level): 1=초기/이완, 2=재교육/안정화, 3=강화/통합
 *   → MUSCLE_DB.phase1/2/3, CURRICULUM_DB.p1/p2/p3 와 매핑
 * ═══════════════════════════════════════════════════════════ */

import type { ExerciseEntry, ExerciseRegion } from './types';

export const EXERCISE_DB: Record<string, ExerciseEntry> = {
  /* ═════════ 발목 (ankle) ═════════ */
  'foam-roll-calf': {
    id: 'foam-roll-calf',
    name: '종아리 폼롤러 SMR',
    nameEn: 'Calf Foam Rolling',
    category: 'mobility',
    regions: ['ankle'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '60초',
    equipment: ['폼롤러'],
    cues: ['아픈 지점에서 5초 멈추기', '발목 천천히 위아래로 움직이기'],
    effect: '비복근·가자미근 긴장을 풀어 발목이 더 깊이 접히게 합니다.',
  },
  'gastroc-stretch': {
    id: 'gastroc-stretch',
    name: '비복근 스트레칭 (무릎 펴고)',
    nameEn: 'Gastrocnemius Stretch',
    category: 'mobility',
    regions: ['ankle'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '45초',
    equipment: ['벽'],
    cues: ['뒷발 발꿈치는 지면에 붙인 채', '몸은 벽 쪽으로 기울이기'],
    effect: '무릎을 편 상태에서의 발목 배굴 가동범위 회복.',
  },
  'soleus-stretch': {
    id: 'soleus-stretch',
    name: '가자미근 스트레칭 (무릎 구부리고)',
    nameEn: 'Soleus Stretch',
    category: 'mobility',
    regions: ['ankle'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '45초',
    equipment: ['벽'],
    cues: ['뒷무릎을 살짝 구부려 가자미근 자극', '발꿈치는 끝까지 지면 유지'],
    effect: '스쿼트 시 발목이 앞으로 들어가는 깊은 배굴 회복.',
  },
  'wall-ankle-mobility': {
    id: 'wall-ankle-mobility',
    name: '벽 발목 배굴 드릴',
    nameEn: 'Wall Ankle Dorsiflexion Drill',
    category: 'mobility',
    regions: ['ankle'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '10회',
    equipment: ['벽'],
    cues: ['무릎이 벽에 닿을 때 발꿈치는 들리지 않도록', '점차 발끝과 벽 사이 거리 넓히기'],
    effect: '체중 부하 상태의 기능적 발목 배굴 훈련.',
  },
  'ankle-cars': {
    id: 'ankle-cars',
    name: 'Ankle CARs',
    nameEn: 'Ankle Controlled Articular Rotations',
    category: 'mobility',
    regions: ['ankle'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 5회',
    equipment: ['맨몸'],
    cues: ['최대한 큰 원을 그리기', '발만 움직이고 정강이는 고정'],
    effect: '발목의 모든 가동범위를 균등하게 깨워 줍니다.',
  },
  'banded-dorsiflexion': {
    id: 'banded-dorsiflexion',
    name: '밴드 저항 발목 배굴',
    nameEn: 'Banded Ankle Dorsiflexion',
    category: 'strength',
    regions: ['ankle'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '15회',
    equipment: ['저항밴드'],
    cues: ['느린 속도로 끝까지 당기기', '발가락만 움직이지 말고 발목 전체로'],
    effect: '약화된 전경골근을 강화해 발목 배굴 능동 가동성 확보.',
  },
  'single-leg-calf-raise': {
    id: 'single-leg-calf-raise',
    name: 'Single Leg Calf Raise',
    nameEn: 'Single Leg Calf Raise',
    category: 'strength',
    regions: ['ankle'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '15회',
    equipment: ['맨몸'],
    cues: ['올라갈 때 빠르게, 내려올 때 3초 천천히', '발 전체로 균등하게 누르기'],
    effect: '편심성 부하로 발목·종아리의 충격 흡수 능력 강화.',
  },
  'slant-board-squat': {
    id: 'slant-board-squat',
    name: 'Slant Board Squat',
    nameEn: 'Slant Board Squat',
    category: 'pattern',
    regions: ['ankle', 'knee'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['경사판 또는 원판'],
    cues: ['발꿈치를 살짝 들어 발목 부담 줄이고 깊이 확보', '점차 경사 낮춰가기'],
    effect: '발목 가동성 부족을 보완하면서 무릎 추적을 동시에 훈련.',
  },
  'single-leg-balance': {
    id: 'single-leg-balance',
    name: 'Single Leg Balance',
    nameEn: 'Single Leg Balance',
    category: 'stability',
    regions: ['ankle', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 30초',
    equipment: ['맨몸'],
    cues: ['발 전체로 지면 강하게 누르기', '익숙해지면 눈을 감고 도전'],
    effect: '발목 고유수용감각을 키워 발목 염좌·삠 부상을 예방.',
  },

  /* ═════════ 무릎 (knee) ═════════ */
  'foam-roll-tfl-itband': {
    id: 'foam-roll-tfl-itband',
    name: 'TFL·IT밴드 폼롤러 SMR',
    nameEn: 'TFL/IT Band Foam Rolling',
    category: 'mobility',
    regions: ['knee', 'hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 60초',
    equipment: ['폼롤러'],
    cues: ['통증 지점에서 호흡 천천히', '엉덩이 위쪽부터 무릎 위까지'],
    effect: '무릎이 안으로 무너지는 패턴의 주범인 외측 긴장을 풀어 줍니다.',
    caution: '극심한 통증·염증 시 중단하고 트레이너에게 알리기',
  },
  'foam-roll-adductor': {
    id: 'foam-roll-adductor',
    name: '내전근 폼롤러 SMR',
    nameEn: 'Adductor Foam Rolling',
    category: 'mobility',
    regions: ['knee', 'hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 60초',
    equipment: ['폼롤러'],
    cues: ['허벅지 안쪽을 폼롤러 위에 얹기', '아픈 지점은 30초 정지 호흡'],
    effect: '무릎 내회전 보상에 기여하는 내전근의 과긴장 완화.',
  },
  'clamshell': {
    id: 'clamshell',
    name: 'Clamshell',
    nameEn: 'Clamshell',
    category: 'stability',
    regions: ['knee', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '20회',
    equipment: ['미니밴드 (선택)'],
    cues: ['골반은 정면 유지, 위쪽 무릎만 열기', '엉덩이 옆쪽이 타들어가는 느낌'],
    effect: '약화된 중둔근을 깨워 무릎이 안으로 무너지는 보상 패턴 차단.',
  },
  'side-lying-hip-abduction': {
    id: 'side-lying-hip-abduction',
    name: 'Side-lying Hip Abduction',
    nameEn: 'Side-lying Hip Abduction',
    category: 'stability',
    regions: ['knee', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 15회',
    equipment: ['맨몸'],
    cues: ['다리는 살짝 뒤쪽으로 든 채 들어올리기', '몸이 앞뒤로 흔들리지 않게'],
    effect: '중둔근 후부 섬유 활성화 — 무릎·골반 동시 안정화.',
  },
  'mini-band-side-walk': {
    id: 'mini-band-side-walk',
    name: 'Mini-band Side Walk',
    nameEn: 'Mini-band Side Walk',
    category: 'pattern',
    regions: ['knee', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '15걸음 × 양방향',
    equipment: ['미니밴드'],
    cues: ['보폭은 작게, 무릎이 발끝 위에 머물도록', '상체는 흔들지 않기'],
    effect: '걷기·계단·점프에서 무릎이 정렬을 유지하는 신경근 훈련.',
  },
  'mini-band-squat': {
    id: 'mini-band-squat',
    name: 'Mini-band Squat',
    nameEn: 'Mini-band Squat',
    category: 'pattern',
    regions: ['knee', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '12회',
    equipment: ['미니밴드'],
    cues: ['밴드를 무릎 위에 두르고 밴드를 밖으로 밀어내며 스쿼트', '무릎이 두 번째 발가락 위'],
    effect: '스쿼트 패턴을 외회전 단서와 함께 재학습.',
  },
  'step-up': {
    id: 'step-up',
    name: 'Step-up',
    nameEn: 'Step-up',
    category: 'strength',
    regions: ['knee', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['박스 또는 계단'],
    cues: ['올라간 다리에 100% 체중 싣기', '내려올 때는 발끝 → 발꿈치 순서로'],
    effect: '단측 지지 능력과 무릎 추적을 동시 훈련.',
  },
  'lateral-step-down': {
    id: 'lateral-step-down',
    name: 'Lateral Step Down',
    nameEn: 'Lateral Step Down',
    category: 'pattern',
    regions: ['knee', 'hip'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['낮은 박스 또는 스텝'],
    cues: ['천천히 내려가며 무릎이 안으로 무너지지 않게', '발꿈치로 살짝 터치 후 다시 올라오기'],
    effect: '편심성 무릎 제어 — 계단 내려갈 때 무릎 통증 예방의 핵심.',
  },
  'bulgarian-split-squat': {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameEn: 'Bulgarian Split Squat',
    category: 'strength',
    regions: ['knee', 'hip'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['벤치'],
    cues: ['앞 다리에 70~80% 체중', '약한 쪽 먼저, 가동범위가 적은 쪽에 횟수 맞추기'],
    effect: '단측 하체 강화 — 좌우 비대칭 교정에 가장 효과적.',
  },
  'single-leg-squat': {
    id: 'single-leg-squat',
    name: 'Single Leg Squat (TRX 보조)',
    nameEn: 'Assisted Single Leg Squat',
    category: 'strength',
    regions: ['knee', 'hip'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['TRX 또는 기둥'],
    cues: ['보조 손은 균형용, 다리가 일을 하도록', '내려갈 때 무릎 정렬 시선으로 확인'],
    effect: '한 다리 스쿼트 능력은 양다리 대비 중둔근 활성도가 30% 높습니다.',
  },

  /* ═════════ 고관절 (hip) ═════════ */
  '90-90-hip-stretch': {
    id: '90-90-hip-stretch',
    name: '90/90 Hip Stretch',
    nameEn: '90/90 Hip Stretch',
    category: 'mobility',
    regions: ['hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한 자세 60초',
    equipment: ['맨몸 (매트)'],
    cues: ['앞·뒤 다리 모두 90도 유지', '척추는 길게, 엉덩이로 인사하듯 앞으로'],
    effect: '고관절 내·외회전 가동범위를 동시에 회복.',
  },
  'half-kneeling-hip-flexor-stretch': {
    id: 'half-kneeling-hip-flexor-stretch',
    name: '반무릎 Hip Flexor Stretch',
    nameEn: 'Half-kneeling Hip Flexor Stretch',
    category: 'mobility',
    regions: ['hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 45초',
    equipment: ['매트'],
    cues: ['엉덩이를 살짝 조이고 골반을 앞으로', '뒷다리 허벅지 앞쪽이 늘어나는 느낌'],
    effect: '오래 앉기로 짧아진 장요근을 풀어 골반 정렬 회복.',
  },
  'thomas-test-stretch': {
    id: 'thomas-test-stretch',
    name: 'Thomas Test Stretch',
    nameEn: 'Thomas Test Stretch',
    category: 'mobility',
    regions: ['hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 45초',
    equipment: ['벤치'],
    cues: ['한 다리는 가슴으로 당겨 골반 고정', '반대 다리는 벤치 밖으로 이완'],
    effect: '장요근 단독 스트레칭 — 단축 정도가 큰 회원에게 우선.',
  },
  'hip-cars': {
    id: 'hip-cars',
    name: 'Hip CARs',
    nameEn: 'Hip Controlled Articular Rotations',
    category: 'mobility',
    regions: ['hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 5회',
    equipment: ['맨몸'],
    cues: ['최대한 큰 원, 골반은 흔들지 않기', '천천히 한 박자씩'],
    effect: '고관절의 모든 가동범위를 균등하게 깨우는 능동 가동성 훈련.',
  },
  'pigeon-stretch': {
    id: 'pigeon-stretch',
    name: '비둘기 자세 (Pigeon Pose)',
    nameEn: 'Pigeon Pose',
    category: 'mobility',
    regions: ['hip'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 60초',
    equipment: ['매트'],
    cues: ['엉덩이가 들리면 쿠션 받치기', '앞쪽 정강이를 매트와 평행에 가깝게'],
    effect: '엉덩이 깊은 외회전근군(이상근 등) 이완.',
  },
  'glute-bridge': {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    nameEn: 'Glute Bridge',
    category: 'stability',
    regions: ['hip', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '12회 (5초 정지)',
    equipment: ['맨몸'],
    cues: ['엉덩이로 들어올리고 허리는 동원하지 않기', '맨 위에서 엉덩이를 강하게 조이기'],
    effect: '대둔근을 깨워 골반 후방 안정화 — 허리 부담 감소.',
  },
  'single-leg-glute-bridge': {
    id: 'single-leg-glute-bridge',
    name: 'Single-leg Glute Bridge',
    nameEn: 'Single-leg Glute Bridge',
    category: 'stability',
    regions: ['hip', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['맨몸'],
    cues: ['골반이 좌우로 기울지 않게', '들어올린 다리를 천장 쪽으로'],
    effect: '단측 대둔근 활성화 — 좌우 골반 안정성 차이 교정.',
  },
  'hip-hinge': {
    id: 'hip-hinge',
    name: 'Dowel Hip Hinge',
    nameEn: 'Dowel Hip Hinge',
    category: 'pattern',
    regions: ['hip', 'spine'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '12회',
    equipment: ['봉 또는 빗자루'],
    cues: ['봉이 머리·등·엉덩이 3점에 닿은 채로', '엉덩이를 뒤로 빼며 인사하듯이'],
    effect: '모든 하체 복합 운동의 기초 — 척추 중립을 지키는 힙 힌지 패턴 학습.',
  },
  'kb-deadlift': {
    id: 'kb-deadlift',
    name: 'KB Deadlift',
    nameEn: 'Kettlebell Deadlift',
    category: 'strength',
    regions: ['hip', 'spine'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['덤벨/케틀벨'],
    cues: ['엉덩이 주도로 들어올리기', '내릴 때 척추 중립 유지'],
    effect: '후방 체인(엉덩이·햄스트링·기립근) 통합 강화.',
  },
  'single-leg-rdl': {
    id: 'single-leg-rdl',
    name: 'Single Leg RDL',
    nameEn: 'Single Leg Romanian Deadlift',
    category: 'pattern',
    regions: ['hip', 'core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['맨몸 또는 덤벨'],
    cues: ['뒷다리·머리·등을 한 직선으로', '균형이 무너지면 무게 줄이기'],
    effect: '단측 후방 체인 + 골반 안정화 동시 훈련.',
  },
  'goblet-squat-to-box': {
    id: 'goblet-squat-to-box',
    name: 'Goblet Squat to Box',
    nameEn: 'Goblet Squat to Box',
    category: 'pattern',
    regions: ['hip', 'knee'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['덤벨/케틀벨', '박스'],
    cues: ['박스에 살짝 터치 후 일어나기', '엉덩이부터 접기'],
    effect: '안전한 깊이 한계 학습 + 힙 주도 스쿼트 패턴 강화.',
  },
  'lateral-lunge': {
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    nameEn: 'Lateral Lunge',
    category: 'pattern',
    regions: ['hip', 'knee'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['맨몸 또는 덤벨'],
    cues: ['옆으로 한 발 크게, 엉덩이 뒤로', '반대 무릎은 펴진 채 유지'],
    effect: '관상면 움직임 강화 — 일상의 옆 움직임/방향 전환 부상 예방.',
  },
  'farmer-carry': {
    id: 'farmer-carry',
    name: 'Farmer Carry',
    nameEn: 'Farmer Carry',
    category: 'pattern',
    regions: ['hip', 'core', 'shoulder'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '30m',
    equipment: ['덤벨/케틀벨'],
    cues: ['어깨를 귀에서 멀리, 갈비뼈 내리고', '걷는 동안 골반 좌우 흔들리지 않게'],
    effect: '동적 코어·견갑·골반 안정성을 한 번에 — 일상 들기·옮기기에 직결.',
  },
  'kb-suitcase-carry': {
    id: 'kb-suitcase-carry',
    name: 'Suitcase Carry',
    nameEn: 'Suitcase Carry',
    category: 'pattern',
    regions: ['hip', 'core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 20m',
    equipment: ['덤벨/케틀벨'],
    cues: ['한 손에만 무게 들고 걷기', '몸이 무게 쪽으로 기울지 않게'],
    effect: '비대칭 부하에서 골반 수평 유지 — 측면 코어·중둔근 강화.',
  },

  /* ═════════ 척추 (spine) / 코어 (core) ═════════ */
  'diaphragmatic-breathing': {
    id: 'diaphragmatic-breathing',
    name: '복식 호흡 + IAP',
    nameEn: 'Diaphragmatic Breathing with IAP',
    category: 'stability',
    regions: ['spine', 'core'],
    level: 1,
    defaultSets: '3세트',
    defaultReps: '5회 (각 10초)',
    equipment: ['매트'],
    cues: ['배꼽이 위·옆·뒤 360도 부풀게', '내쉴 때 갈비뼈 안으로 모으기'],
    effect: '코어의 시작은 호흡 — 복강내압(IAP)으로 척추를 안에서 지탱.',
  },
  '90-90-hip-lift': {
    id: '90-90-hip-lift',
    name: '90/90 Hip Lift',
    nameEn: '90/90 Hip Lift',
    category: 'stability',
    regions: ['spine', 'core'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '5회 (각 5초)',
    equipment: ['벽 또는 박스'],
    cues: ['두 발을 벽에 대고 무릎·고관절 90도', '꼬리뼈를 살짝 들어올리며 호흡 내쉬기'],
    effect: '횡격막·골반저·복횡근의 동시 활성화 — 코어 협응 회복.',
  },
  'cat-camel': {
    id: 'cat-camel',
    name: '캣-카우',
    nameEn: 'Cat-Camel',
    category: 'mobility',
    regions: ['spine'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '10회',
    equipment: ['매트'],
    cues: ['척추 한 마디씩 천천히 굴곡·신전', '호흡과 박자 맞추기'],
    effect: '척추 분절 가동성 회복 — 굳은 등을 깨우는 가장 안전한 시작.',
  },
  'mcgill-curl-up': {
    id: 'mcgill-curl-up',
    name: 'McGill Curl-up',
    nameEn: 'McGill Curl-up',
    category: 'stability',
    regions: ['spine', 'core'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '8회',
    equipment: ['매트'],
    cues: ['머리·어깨만 살짝 들기, 허리는 바닥에 둔 채', '목이 아프면 손으로 머리 받치기'],
    effect: 'McGill의 척추 안정화 빅3 중 하나 — 허리 부담 없는 복근 활성화.',
  },
  'dead-bug': {
    id: 'dead-bug',
    name: 'Dead Bug',
    nameEn: 'Dead Bug',
    category: 'stability',
    regions: ['core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['매트'],
    cues: ['허리는 바닥에서 절대 떨어지지 않기', '반대쪽 팔·다리 천천히 동시에'],
    effect: '복횡근·다열근 공동 수축 — 사지가 움직여도 척추가 흔들리지 않는 통제력.',
  },
  'bird-dog': {
    id: 'bird-dog',
    name: 'Bird Dog',
    nameEn: 'Bird Dog',
    category: 'stability',
    regions: ['core', 'spine'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회 (5초 정지)',
    equipment: ['매트'],
    cues: ['손·반대쪽 발이 일직선', '엉덩이가 좌우로 흔들리지 않게'],
    effect: 'McGill 빅3 — 견갑부터 골반까지 대각선 안정화 패턴 학습.',
  },
  'plank': {
    id: 'plank',
    name: 'Plank',
    nameEn: 'Front Plank',
    category: 'stability',
    regions: ['core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '30~60초',
    equipment: ['매트'],
    cues: ['엉덩이 떨어지지 않게', '갈비뼈와 골반을 가깝게 (복부 조이기)'],
    effect: '등척성 코어 안정화 — 복압 유지 능력의 기본기.',
  },
  'side-plank': {
    id: 'side-plank',
    name: 'Side Plank',
    nameEn: 'Side Plank',
    category: 'stability',
    regions: ['core', 'hip'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 20~60초',
    equipment: ['매트'],
    cues: ['엉덩이를 천장 쪽으로 끌어올리기', '몸은 어깨~발끝 일직선'],
    effect: 'McGill 빅3 — 측면 코어(요방형근·복사근) 강화.',
  },
  'pallof-press': {
    id: 'pallof-press',
    name: 'Pallof Press',
    nameEn: 'Pallof Press',
    category: 'stability',
    regions: ['core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['저항밴드 또는 케이블'],
    cues: ['몸통이 회전 저항에 끌려가지 않게', '팔만 앞뒤로 천천히'],
    effect: '반회전 저항(anti-rotation) — 일상 회전·꼬임 동작에서 허리 보호.',
  },
  'hollow-hold': {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    nameEn: 'Hollow Body Hold',
    category: 'stability',
    regions: ['core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '20~30초',
    equipment: ['매트'],
    cues: ['허리가 바닥에 닿은 채 팔·다리 들기', '팔다리 점차 길게 빼기로 강도 조절'],
    effect: '전방 코어 등척성 강화 — 체조·러닝 자세 안정화.',
  },

  /* ═════════ 어깨 (shoulder) / 흉추 ═════════ */
  'pec-minor-doorway-stretch': {
    id: 'pec-minor-doorway-stretch',
    name: '소흉근 도어웨이 스트레칭',
    nameEn: 'Pec Minor Doorway Stretch',
    category: 'mobility',
    regions: ['shoulder'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '45초',
    equipment: ['문틀'],
    cues: ['팔꿈치 90도, 한 발 앞으로 내딛기', '가슴 앞쪽이 늘어나는 느낌'],
    effect: '둥근 어깨의 주범 소흉근 단축을 풀어 어깨 후방 정렬 회복.',
  },
  'lat-stretch': {
    id: 'lat-stretch',
    name: '광배근 스트레칭',
    nameEn: 'Latissimus Dorsi Stretch',
    category: 'mobility',
    regions: ['shoulder', 'spine'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '45초',
    equipment: ['벽 또는 봉'],
    cues: ['팔을 머리 위로 길게 뻗고 몸을 반대쪽으로', '겨드랑이~허리가 늘어나는 느낌'],
    effect: '오버헤드 가동성 제한의 흔한 원인 — 광배근 단축 해소.',
  },
  'foam-roll-thoracic': {
    id: 'foam-roll-thoracic',
    name: '흉추 폼롤러 익스텐션',
    nameEn: 'Thoracic Foam Rolling Extension',
    category: 'mobility',
    regions: ['spine', 'shoulder'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '10회',
    equipment: ['폼롤러'],
    cues: ['폼롤러를 어깨뼈 아래에 두고 천천히 신전', '허리가 꺾이지 않게 엉덩이 살짝 들기'],
    effect: '굳은 흉추를 깨워 어깨·목 부담 동시 감소.',
  },
  'open-book': {
    id: 'open-book',
    name: '오픈 북 스트레칭',
    nameEn: 'Open Book Stretch',
    category: 'mobility',
    regions: ['spine', 'shoulder'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 10회',
    equipment: ['매트'],
    cues: ['옆으로 누워 위쪽 팔을 책 펼치듯 회전', '시선은 손끝을 따라가기'],
    effect: '흉추 회전 가동성 — 골프·테니스·운전 동작에 필요.',
  },
  'sleeper-stretch': {
    id: 'sleeper-stretch',
    name: 'Sleeper Stretch',
    nameEn: 'Sleeper Stretch',
    category: 'mobility',
    regions: ['shoulder'],
    level: 1,
    defaultSets: '2세트',
    defaultReps: '한쪽 45초',
    equipment: ['매트'],
    cues: ['옆으로 누워 어깨·팔꿈치 90도', '반대 손으로 손목을 천천히 바닥 쪽으로'],
    effect: '어깨 내회전 제한 회복 — 던지기·라켓 종목에 특히 유용.',
  },
  'wall-slide': {
    id: 'wall-slide',
    name: 'Wall Slide',
    nameEn: 'Wall Slide',
    category: 'stability',
    regions: ['shoulder', 'spine'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '15회',
    equipment: ['벽'],
    cues: ['손·팔꿈치·등·엉덩이를 벽에 붙인 채', '천천히 만세 후 다시 W로'],
    effect: '견갑 안정화 + 흉추 가동성 — 어깨 충돌 예방의 기본기.',
  },
  'wall-angel': {
    id: 'wall-angel',
    name: 'Wall Angel',
    nameEn: 'Wall Angel',
    category: 'stability',
    regions: ['shoulder', 'spine'],
    level: 2,
    defaultSets: '2세트',
    defaultReps: '10회',
    equipment: ['벽'],
    cues: ['머리·등·엉덩이 벽 접촉 유지', '천사 날개 모양으로 위아래'],
    effect: '하부 승모근·전거근 활성화 — 어깨가 자연스럽게 뒤로 정렬.',
  },
  'band-face-pull': {
    id: 'band-face-pull',
    name: '밴드 Face Pull',
    nameEn: 'Band Face Pull',
    category: 'stability',
    regions: ['shoulder', 'spine'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '15회',
    equipment: ['저항밴드 또는 케이블'],
    cues: ['엄지손가락이 뒤를 향하도록 외회전', '날개뼈 뒤 주머니에 넣듯이'],
    effect: '뒤어깨 + 외회전근 + 하부 승모근 동시 강화 — 둥근 어깨 교정.',
  },
  'ytw-raises': {
    id: 'ytw-raises',
    name: 'Y-T-W Raises (엎드려)',
    nameEn: 'Prone Y-T-W Raises',
    category: 'stability',
    regions: ['shoulder', 'spine'],
    level: 2,
    defaultSets: '2세트',
    defaultReps: '각 자세 10회',
    equipment: ['매트 또는 벤치'],
    cues: ['엄지를 천장으로 올리며 들기', '날개뼈를 등 가운데로 모으기'],
    effect: '하부 승모근·전거근 — 어깨 후방 정렬에 직결되는 약화 근육.',
  },
  'side-lying-external-rotation': {
    id: 'side-lying-external-rotation',
    name: 'Side-lying External Rotation',
    nameEn: 'Side-lying External Rotation',
    category: 'strength',
    regions: ['shoulder'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '한쪽 15회',
    equipment: ['덤벨 (1~2kg)'],
    cues: ['팔꿈치는 옆구리에 고정', '손목만 회전하지 말고 어깨로 돌리기'],
    effect: '회전근개 후부 강화 — 어깨 충돌·통증의 가장 흔한 원인 해소.',
  },
  'kb-bottoms-up-press': {
    id: 'kb-bottoms-up-press',
    name: 'KB Bottoms-up Press',
    nameEn: 'Kettlebell Bottoms-up Press',
    category: 'strength',
    regions: ['shoulder', 'core'],
    level: 3,
    defaultSets: '2세트',
    defaultReps: '한쪽 8회',
    equipment: ['케틀벨 (가벼운 것)'],
    cues: ['케틀벨을 거꾸로 잡고 균형 유지', '코어부터 단단히 잠그기'],
    effect: '회전근개 + 견갑 + 코어 공동 수축 — 안전한 오버헤드 진입.',
  },
  'half-kneeling-press': {
    id: 'half-kneeling-press',
    name: 'Half-kneeling KB Press',
    nameEn: 'Half-kneeling Kettlebell Press',
    category: 'strength',
    regions: ['shoulder', 'core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 8회',
    equipment: ['덤벨/케틀벨'],
    cues: ['뒷다리 무릎-앞다리 발끝 일직선', '엉덩이를 살짝 조여 골반 후방경사'],
    effect: '코어와 연결된 안정적 오버헤드 패턴 학습.',
  },
  'landmine-press': {
    id: 'landmine-press',
    name: 'Landmine Press',
    nameEn: 'Landmine Press',
    category: 'strength',
    regions: ['shoulder', 'core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['바벨 + 랜드마인 어태치먼트'],
    cues: ['바벨이 사선으로 올라가도록', '발끝~머리까지 한 줄 유지'],
    effect: '완전 오버헤드 진입 전 단계 — 어깨 가동성 부족자에게 안전.',
  },
  'pull-up': {
    id: 'pull-up',
    name: 'Pull-up 또는 Lat Pulldown',
    nameEn: 'Pull-up or Lat Pulldown',
    category: 'strength',
    regions: ['shoulder', 'spine'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['풀업바 또는 케이블'],
    cues: ['턱이 봉 위까지 올라가도록', '내려갈 때 천천히 (편심성 강조)'],
    effect: '등 광배근·중·하부 승모근 통합 강화.',
  },
  'seated-cable-row': {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    nameEn: 'Seated Cable Row',
    category: 'strength',
    regions: ['spine', 'shoulder'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '12회',
    equipment: ['케이블'],
    cues: ['상체 흔들지 않고 팔로만 당기기', '날개뼈를 등 가운데로 모으기'],
    effect: '중부 승모근·능형근 강화 — 라운드 숄더 균형.',
  },
  'trx-row': {
    id: 'trx-row',
    name: 'TRX Row',
    nameEn: 'TRX Inverted Row',
    category: 'strength',
    regions: ['spine', 'shoulder', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '12회',
    equipment: ['TRX'],
    cues: ['몸은 일직선 유지', '가슴이 손까지 올라오게'],
    effect: '체중을 활용한 후방 체인 강화 — 초중급 등 운동 입문.',
  },
  'push-up': {
    id: 'push-up',
    name: 'Push-up',
    nameEn: 'Push-up',
    category: 'strength',
    regions: ['shoulder', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['맨몸'],
    cues: ['몸 일직선 유지 — 엉덩이 처지거나 들리지 않게', '팔꿈치는 몸통에서 45도'],
    effect: '전방 사슬 + 코어 통합 — 가장 검증된 상체 기본기.',
  },

  /* ═════════ 복합 / 강화 ═════════ */
  'goblet-squat': {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    nameEn: 'Goblet Squat',
    category: 'strength',
    regions: ['hip', 'knee', 'core'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['덤벨/케틀벨'],
    cues: ['가슴 앞에 무게 — 자연스럽게 코어 활성', '엉덩이부터 접기, 무릎이 발끝 위'],
    effect: '안전한 진입의 베스트 — 척추 중립 큐잉과 함께 사용.',
  },
  'heel-elevated-goblet-squat': {
    id: 'heel-elevated-goblet-squat',
    name: 'Heel Elevated Goblet Squat',
    nameEn: 'Heel Elevated Goblet Squat',
    category: 'pattern',
    regions: ['hip', 'knee', 'ankle'],
    level: 2,
    defaultSets: '3세트',
    defaultReps: '10회',
    equipment: ['덤벨/케틀벨', '원판'],
    cues: ['뒷꿈치 1~2cm 들어 발목 부담 감소', '점차 평지에 가깝게 progression'],
    effect: '발목 가동성 부족 회원의 안전한 깊은 스쿼트 진입로.',
  },
  'trap-bar-deadlift': {
    id: 'trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    nameEn: 'Trap Bar Deadlift',
    category: 'strength',
    regions: ['hip', 'spine'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '8회',
    equipment: ['트랩바 (헥스바)'],
    cues: ['엉덩이로 들기 시작', '척추 중립을 유지한 채 끝까지 서기'],
    effect: '바벨 데드리프트 대비 척추 부담 ↓, 단일 운동 최고의 후방 체인 강화.',
  },
  'barbell-back-squat': {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    nameEn: 'Barbell Back Squat',
    category: 'strength',
    regions: ['hip', 'knee', 'core'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '8회',
    equipment: ['바벨'],
    cues: ['바를 등 위에 안정적으로', '깊이는 허리 중립이 깨지기 직전까지'],
    effect: '하체 강화의 표준 — 가동성·안정성 충분히 확보 후 진입.',
  },
  'turkish-get-up': {
    id: 'turkish-get-up',
    name: 'Turkish Get-up',
    nameEn: 'Turkish Get-up',
    category: 'pattern',
    regions: ['shoulder', 'hip', 'core'],
    level: 3,
    defaultSets: '2세트',
    defaultReps: '한쪽 3회',
    equipment: ['덤벨/케틀벨'],
    cues: ['천천히 — 5분짜리 1렙도 OK', '시선은 항상 무게에'],
    effect: '전신 통합 — 어깨 안정성 + 코어 + 고관절 가동성을 한 번에.',
  },
  'box-step-down': {
    id: 'box-step-down',
    name: 'Box Step-down (점프 착지 준비)',
    nameEn: 'Box Step-down',
    category: 'pattern',
    regions: ['knee', 'hip', 'ankle'],
    level: 3,
    defaultSets: '3세트',
    defaultReps: '한쪽 10회',
    equipment: ['낮은 박스'],
    cues: ['천천히 내려가며 무릎 정렬 확인', '익숙해지면 양발 점프 착지 → 한발로 progression'],
    effect: '편심성 제어와 점프 착지 충격 흡수 능력 — 스포츠·러닝 부상 예방.',
  },
};

/* ───────────────────────────────────────────────────────────
 * 헬퍼
 * ─────────────────────────────────────────────────────────── */

export function getExercise(id: string): ExerciseEntry | null {
  return EXERCISE_DB[id] ?? null;
}

/** ExerciseRef → 표시용 fallback 문자열 (한글명 + reps).
 *  카드 UI가 깨졌을 때나 기존 string[] 호환 위해 사용. */
export function exerciseRefToString(ref: { id: string; setsOverride?: string; repsOverride?: string }): string {
  const ex = getExercise(ref.id);
  if (!ex) return ref.id;
  const reps = ref.repsOverride ?? ex.defaultReps;
  const sets = ref.setsOverride ?? ex.defaultSets;
  return `${ex.name} ${reps} × ${sets}`;
}

export function filterExercisesByRegion(region: ExerciseRegion): ExerciseEntry[] {
  return Object.values(EXERCISE_DB).filter((e) => e.regions.includes(region));
}

export function exerciseCount(): number {
  return Object.keys(EXERCISE_DB).length;
}
